export interface LectureItem {
  id: string;
  lectureNumber: number;
  title: string;
  videoId: string;
  duration: string;
  instructor: string;
  description?: string;
}

export interface StudyModule {
  id: string;
  moduleNumber: number;
  moduleLabel: string;
  title: string;
  subject: string;
  category: "core" | "non-core" | "lecture" | "temp_pdf";
  description: string;
  lectures: LectureItem[]; // Array of YT video lectures for this module
  pdfUrl: string;
  isTemp?: boolean;
}

export const MODULES_CATALOG: StudyModule[] = [
  // ==================== CORE SYLLABUS (1ST YEAR B.TECH) ====================
  // 1. Mathematics-II (Paper Code: BS-M201) - Prioritized Mentor: Dr. Gajendra Purohit
  {
    id: "math2-bs201-mod1",
    moduleNumber: 1,
    moduleLabel: "MODULE 1",
    title: "Ordinary Differential Equations (ODE) of 1st & 2nd Order",
    subject: "Mathematics-II (BS-M201)",
    category: "core",
    description: "First order & first degree: Exact equations, integrating factors, Bernoulli's equation. Higher degree Clairaut's equation. Second order linear ODEs with constant coefficients (CF & PI), D-operator methods, Method of variation of parameters, Cauchy-Euler equations. [10L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "m2-m1-l1",
        lectureNumber: 1,
        title: "Exact & Reducible Differential Equations: Concept & Solved Problems",
        videoId: "Ecc7SHqymPo",
        duration: "12 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Necessary & sufficient condition for exactness, integrating factor rules, and general solutions of first-order ODEs.",
      },
      {
        id: "m2-m1-l2",
        lectureNumber: 2,
        title: "Linear Higher Order Differential Equations: Rules of CF & PI",
        videoId: "tHqx1qxA8q4",
        duration: "34 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Finding complementary functions (CF) and particular integrals (PI) using D-operator shortcuts for polynomial, exponential, and trigonometric RHS.",
      },
      {
        id: "m2-m1-l3",
        lectureNumber: 3,
        title: "Method of Variation of Parameters & Wronskian Evaluation",
        videoId: "jiQ2sX5wGwM",
        duration: "17 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Evaluating particular integrals using Wronskian determinant for second-order ODEs and Cauchy-Euler homogeneous equations.",
      },
    ],
  },
  {
    id: "math2-bs201-mod2",
    moduleNumber: 2,
    moduleLabel: "MODULE 2",
    title: "Basics of Graph Theory: Matrices, Circuits & Isomorphism",
    subject: "Mathematics-II (BS-M201)",
    category: "core",
    description: "Graphs, Digraphs, Weighted graph, Connected/Disconnected graphs, Complement, Regular, Complete, Subgraphs; Walks, Paths, Circuits, Euler Graph, Matrix representation, Adjacency and incidence matrices, Graph isomorphism, Bipartite graph. [5L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "m2-m2-l1",
        lectureNumber: 1,
        title: "Graph Theory: Walks, Paths, Circuits, Eulerian & Hamiltonian Graphs",
        videoId: "tuitCMLwPAE",
        duration: "16 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Trail, path, circuit definitions, Euler circuit conditions, Konigsberg bridge problem, and Hamiltonian paths.",
      },
      {
        id: "m2-m2-l2",
        lectureNumber: 2,
        title: "Matrix Representation of Graphs: Adjacency and Incidence Matrices",
        videoId: "17erhldpZ8E",
        duration: "20 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Constructing adjacency and incidence matrices, matrix properties, connected components, and path count theorems.",
      },
      {
        id: "m2-m2-l3",
        lectureNumber: 3,
        title: "Graph Isomorphism, Regular, Complete & Bipartite Graphs",
        videoId: "mAaLIiSmI08",
        duration: "16 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Checking graph isomorphism invariants (vertices, edges, degree sequence), complete bipartite graphs, and Kuratowski's theorem.",
      },
    ],
  },
  {
    id: "math2-bs201-mod3",
    moduleNumber: 3,
    moduleLabel: "MODULE 3",
    title: "Laplace Transform: Theory, Convolution & ODE Applications",
    subject: "Mathematics-II (BS-M201)",
    category: "core",
    description: "Introduction to integral transformation, functions of exponential order, Definition & existence of LT, elementary functions, properties, evaluation of integrals using LT, periodic/step functions. Inverse LT, Convolution Theorem, solution of linear ODEs with constant coefficients. [10L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "m2-m3-l1",
        lectureNumber: 1,
        title: "Laplace Transform: Definition, Existence & Elementary Functions",
        videoId: "OA1OJrfpP20",
        duration: "18 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Formulas for polynomials, exponentials, sine/cosine, hyperbolic functions, first shifting theorem, and existence conditions.",
      },
      {
        id: "m2-m3-l2",
        lectureNumber: 2,
        title: "Inverse Laplace Transform & Convolution Theorem with Examples",
        videoId: "bfWu14Ny-tc",
        duration: "19 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Evaluating inverse Laplace transforms using partial fractions, derivative/integral properties, and Convolution Theorem integral.",
      },
      {
        id: "m2-m3-l3",
        lectureNumber: 3,
        title: "Solution of Ordinary Differential Equations using Laplace Transforms",
        videoId: "KaRx67h5xzk",
        duration: "24 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Solving initial value differential equations (IVP) directly in s-domain and transforming back to time-domain solutions.",
      },
    ],
  },
  {
    id: "math2-bs201-mod4",
    moduleNumber: 4,
    moduleLabel: "MODULE 4",
    title: "Complex Variables: Analytic Functions & Complex Integration",
    subject: "Mathematics-II (BS-M201)",
    category: "core",
    description: "Complex functions, Limit, Continuity, Differentiability. Analytic functions, Cauchy-Riemann Equations. Harmonic and Conjugate Harmonic functions. Milne-Thomson method. Conformal mappings, Bilinear/Mobius transformations. Complex Integration: Contour, Cauchy's theorem, Cauchy-Goursat theorem, Cauchy's integral formula for derivatives. [12L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "m2-m4-l1",
        lectureNumber: 1,
        title: "Complex Analysis: Analytic Functions & Cauchy-Riemann Equations",
        videoId: "t9xW7UaZwZ0",
        duration: "12 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Cauchy-Riemann equations in Cartesian and polar forms, necessary and sufficient conditions for differentiability and analyticity.",
      },
      {
        id: "m2-m4-l2",
        lectureNumber: 2,
        title: "Milne-Thomson Method & Finding Harmonic Conjugate Functions",
        videoId: "ABNW9FcZ5zQ",
        duration: "17 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Direct construction of analytic function f(z) = u + iv when real or imaginary part is given, and orthogonality of curves.",
      },
      {
        id: "m2-m4-l3",
        lectureNumber: 3,
        title: "Cauchy's Integral Theorem & Integral Formula for Derivatives",
        videoId: "fSoQxuVdKIs",
        duration: "21 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Evaluation of line integrals along closed contours, Cauchy-Goursat theorem, and higher derivatives of analytic functions.",
      },
    ],
  },
  {
    id: "math2-bs201-mod5",
    moduleNumber: 5,
    moduleLabel: "MODULE 5",
    title: "Zeros, Singularities & Cauchy's Residue Theorem",
    subject: "Mathematics-II (BS-M201)",
    category: "core",
    description: "Zeros of analytic functions, singularities (isolated, non-isolated, essential). Poles (simple, pole of order m). Taylor's series, Laurent's series. Residue at poles, Cauchy's Residue theorem, evaluation of definite and improper contour integrals using Bromwich contour. [8L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "m2-m5-l1",
        lectureNumber: 1,
        title: "Laurent's Series, Types of Singularities & Poles of Order m",
        videoId: "gUmIrJRXDSs",
        duration: "19 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Expansion in annular domains, principal part analysis, removable singularities, essential singularities, and poles.",
      },
      {
        id: "m2-m5-l2",
        lectureNumber: 2,
        title: "Cauchy's Residue Theorem & Contour Integration Techniques",
        videoId: "4yC4IXcMKJg",
        duration: "21 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Calculation of residues at simple poles and multiple poles, Cauchy's residue theorem, and evaluation of real definite trigonometric/rational integrals.",
      },
    ],
  },

  // 2. Physics-I (Paper Code: BS-PH 101 / BS-PH 201) - Prioritized Mentors: Pradeep Giri Sir & Gautam Varde
  {
    id: "phys1-bsph101-mod1",
    moduleNumber: 1,
    moduleLabel: "MODULE 1",
    title: "Vector Calculus, Oscillations, Damping & Resonance",
    subject: "Physics-I (BS-PH 101 / BS-PH 201)",
    category: "core",
    description: "Vector calculus: Gradient, Divergence, Curl, Line/Surface/Volume integrals, Divergence and Stokes' theorems. Simple Harmonic Oscillations, compound pendulum, coupled oscillations. Damped oscillations: Overdamped, critical, oscillatory damping, relaxation time, log decrement. Forced oscillations: Resonance, quality factor, sharpness of resonance. [10L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "ph-m1-l1",
        lectureNumber: 1,
        title: "Oscillations, Damped & Forced Harmonic Motion and Resonance",
        videoId: "DuNruwnXHQ8",
        duration: "21 mins",
        instructor: "Pradeep Giri Sir",
        description: "Comprehensive derivation of angular SHM, damped harmonic oscillations, mechanical impedance, and resonance conditions.",
      },
      {
        id: "ph-m1-l2",
        lectureNumber: 2,
        title: "Damped Harmonic Motion: Differential Equation & Log Decrement",
        videoId: "AkovfMs9V6s",
        duration: "19 mins",
        instructor: "Gautam Varde",
        description: "Second-order differential equation for damped oscillators, heavy damping vs critical damping, and logarithmic decrement formulas.",
      },
      {
        id: "ph-m1-l3",
        lectureNumber: 3,
        title: "Forced Vibrations, Mechanical Impedance & Sharpness of Resonance",
        videoId: "6zbge3-tCcQ",
        duration: "18 mins",
        instructor: "Gautam Varde",
        description: "Driving periodic force response, amplitude resonance frequency, quality factor (Q-factor), and bandwidth sharpness.",
      },
    ],
  },
  {
    id: "phys1-bsph101-mod2",
    moduleNumber: 2,
    moduleLabel: "MODULE 2",
    title: "Optics: Interference, Diffraction, Polarization & Lasers",
    subject: "Physics-I (BS-PH 101 / BS-PH 201)",
    category: "core",
    description: "Interference: Division of wavefront and amplitude, Newton's rings (wavelength and thickness), thin film interference, anti-reflection coatings. Diffraction: Fresnel and Fraunhofer diffraction (single slit, double slit, N-slit). Polarization: Brewster's law, Malus law, optical activity. Lasers: Einstein coefficients, He-Ne and solid state lasers. [11L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "ph-m2-l1",
        lectureNumber: 1,
        title: "Newton's Rings & Thin Film Interference Experimental Setup",
        videoId: "xODNLZlrLbQ",
        duration: "26 mins",
        instructor: "Gautam Varde",
        description: "Interference in air wedge film, circular fringes, dark central spot, and measuring wavelength and refractive index of liquids.",
      },
      {
        id: "ph-m2-l2",
        lectureNumber: 2,
        title: "Fresnel & Fraunhofer Diffraction at Single Slit & Gratings",
        videoId: "TA9ROQkJ6KM",
        duration: "21 mins",
        instructor: "Gautam Varde",
        description: "Fraunhofer single slit pattern, central maxima width, double slit interference-diffraction overlap, and grating resolving power.",
      },
      {
        id: "ph-m2-l3",
        lectureNumber: 3,
        title: "LASER: Fundamentals, Einstein Coefficients & He-Ne Working",
        videoId: "Xy67j-KZytY",
        duration: "31 mins",
        instructor: "Pradeep Giri Sir",
        description: "Spontaneous vs stimulated emission, population inversion, optical pumping, Helium-Neon gas laser mechanics, and industrial applications.",
      },
    ],
  },
  {
    id: "phys1-bsph101-mod3",
    moduleNumber: 3,
    moduleLabel: "MODULE 3",
    title: "Statistical Mechanics: Phase Space & Quantum Ensembles",
    subject: "Physics-I (BS-PH 101 / BS-PH 201)",
    category: "core",
    description: "Phase Space (mu- and Gamma-phase space), Macro states and Microstates, Density of States, Statistical Ensemble and Thermodynamic Probability. Classical Statistical systems (Maxwell-Boltzmann) and quantum statistical systems (Fermi-Dirac and Bose-Einstein Statistics) with engineering applications. [5L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "ph-m3-l1",
        lectureNumber: 1,
        title: "Maxwell-Boltzmann, Fermi-Dirac & Bose-Einstein Distributions",
        videoId: "m_0R2bGk0U8",
        duration: "52 mins",
        instructor: "Physics Talks",
        description: "Distinguishable vs indistinguishable particles, thermodynamic probability, Pauli exclusion constraint, and distribution functions.",
      },
      {
        id: "ph-m3-l2",
        lectureNumber: 2,
        title: "Comparing Classical vs Quantum Statistical Systems in Solids",
        videoId: "e9TQs-EDiUs",
        duration: "4 mins",
        instructor: "Professor Nano",
        description: "Comparison of occupation probabilities, Fermi energy in metals, photon gas (Bose-Einstein), and classical limits.",
      },
    ],
  },
  {
    id: "phys1-bsph101-mod4",
    moduleNumber: 4,
    moduleLabel: "MODULE 4",
    title: "Quantum Mechanics: Wave Packets & Schrodinger Equations",
    subject: "Physics-I (BS-PH 101 / BS-PH 201)",
    category: "core",
    description: "Blackbody Radiation (Planck, Wien, Stefan-Boltzmann, Rayleigh-Jeans), Compton Effect. De Broglie hypothesis, Heisenberg's Uncertainty Principle, Group and phase velocity. Wave function postulates, operators, eigenvalues, Schrodinger's time-dependent and time-independent wave equations, Particle in 1D/3D box, degeneracy. [10L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "ph-m4-l1",
        lectureNumber: 1,
        title: "Quantum Mechanics: De Broglie Matter Waves & Dual Nature",
        videoId: "KKd-TGEo_1E",
        duration: "45 mins",
        instructor: "BTech Wallah",
        description: "Historical failure of classical physics, ultraviolet catastrophe, Planck radiation formula, and matter wave wavelengths.",
      },
      {
        id: "ph-m4-l2",
        lectureNumber: 2,
        title: "Heisenberg's Uncertainty Principle & Wave Function Postulates",
        videoId: "W7Ke6oZ66QU",
        duration: "16 mins",
        instructor: "Gautam Varde",
        description: "Position-momentum uncertainty, phase and group velocity relations, wave packet spread, and probability density.",
      },
      {
        id: "ph-m4-l3",
        lectureNumber: 3,
        title: "Schrodinger Time-Independent Equation & 1D Potential Box",
        videoId: "86RJiteOYa4",
        duration: "22 mins",
        instructor: "EDVARA Engineers",
        description: "Setting up boundary conditions for an infinite potential well, quantization of energy levels, wave function normalization, and zero-point energy.",
      },
    ],
  },
  {
    id: "phys1-bsph101-mod5",
    moduleNumber: 5,
    moduleLabel: "MODULE 5",
    title: "Dielectric Polarization & Magnetic Properties of Materials",
    subject: "Physics-I (BS-PH 101 / BS-PH 201)",
    category: "core",
    description: "Dielectric Polarization: Fundamentals, microscopic/macroscopic field, Electronic, Ionic, Orientational, Space charge polarization, dielectric loss, loss tangent. Magnetic Properties: Classification (Dia, Para, Ferro, Anti-ferro, Ferri, Superparamagnetic), Curie temperature, magnetic domains, hysteresis loop, hard and soft magnetic materials. [6L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "ph-m5-l1",
        lectureNumber: 1,
        title: "Dielectrics & Polarization Mechanisms in Solids",
        videoId: "g9sPs-ZCNss",
        duration: "19 mins",
        instructor: "Gautam Varde",
        description: "Electric dipole moment, Clausius-Mossotti equation, frequency dependence of polarizability, and dielectric breakdown.",
      },
      {
        id: "ph-m5-l2",
        lectureNumber: 2,
        title: "Magnetic Materials: Dia, Para, Ferromagnetism & Hysteresis",
        videoId: "-erIMlT8iMs",
        duration: "26 mins",
        instructor: "Pradeep Giri Sir",
        description: "Magnetic susceptibility, domain theory of ferromagnetism, B-H hysteresis curve, retentivity, coercivity, and soft vs hard magnets.",
      },
    ],
  },

  // 3. Basic Electrical and Electronics Engineering (Paper Code: ES-EE101 / ES-EE201)
  {
    id: "beee-esee101-mod1",
    moduleNumber: 1,
    moduleLabel: "MODULE 1",
    title: "Electromagnetism & Magnetic Circuits",
    subject: "Basic Electrical and Electronics Engineering (ES-EE101 / ES-EE201)",
    category: "core",
    description: "Magnetic circuits, Analogous quantities in magnetic and electric circuits, Faraday's law, self and mutual inductance, Hysteretic and Eddy current losses, B-H loop. [3L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "ee-m1-l1",
        lectureNumber: 1,
        title: "B-H Curve, Hysteresis Loop & Eddy Current Losses",
        videoId: "6E19al9dEno",
        duration: "12 mins",
        instructor: "Gautam Varde",
        description: "Magnetic field intensity (H), magnetic flux density (B), magnetic saturation, retentivity, coercivity, and energy loss calculation.",
      },
      {
        id: "ee-m1-l2",
        lectureNumber: 2,
        title: "Magnetic Circuits, Flux & Inductance Analysis",
        videoId: "62lmfPki868",
        duration: "28 mins",
        instructor: "GATE Academy (Ranjan Rai)",
        description: "MMF, reluctance, permeance, comparison with electric circuits (Ohm's law analogy), and Faraday's law of electromagnetic induction.",
      },
    ],
  },
  {
    id: "beee-esee101-mod2",
    moduleNumber: 2,
    moduleLabel: "MODULE 2",
    title: "Circuits Analysis: DC Network Theorems & AC Fundamentals",
    subject: "Basic Electrical and Electronics Engineering (ES-EE101 / ES-EE201)",
    category: "core",
    description: "Linear & non-linear circuits, Kirchhoff's laws (KCL/KVL), Nodal & Mesh analysis. Principle of superposition, Source transformation, Thevenin's and Norton's Theorems. AC fundamentals: Sinusoidal waveforms, RMS and Average values, peak & form factors, phasor representation, AC series circuits (RL, RC, RLC), power factor, active and reactive power. [10L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "ee-m2-l1",
        lectureNumber: 1,
        title: "DC Circuit Mesh Analysis & Kirchhoff's Laws (KVL/KCL)",
        videoId: "lSS0OQQhr0E",
        duration: "31 mins",
        instructor: "Pradeep Giri Sir",
        description: "Systematic nodal and mesh equations, matrix solution, and handling dependent and independent voltage/current sources.",
      },
      {
        id: "ee-m2-l2",
        lectureNumber: 2,
        title: "Thevenin's & Norton's Network Reduction Theorems",
        videoId: "_h62NLQ33DA",
        duration: "17 mins",
        instructor: "Gautam Varde",
        description: "Finding Vth, Rth, and Norton equivalent current IN, maximum power transfer condition, and Superposition theorem.",
      },
      {
        id: "ee-m2-l3",
        lectureNumber: 3,
        title: "AC Fundamentals: RMS, Average Values, Phasor & Power Factor",
        videoId: "ndoNMPJgjIo",
        duration: "45 mins",
        instructor: "Education Hub Electrical",
        description: "Generation of alternating EMF, form factor, peak factor, complex phasor notation, impedance triangle, and power in RLC series circuits.",
      },
    ],
  },
  {
    id: "beee-esee101-mod3",
    moduleNumber: 3,
    moduleLabel: "MODULE 3",
    title: "Single Phase Transformers: Principles, Tests & Efficiency",
    subject: "Basic Electrical and Electronics Engineering (ES-EE101 / ES-EE201)",
    category: "core",
    description: "Core and shell type construction, ideal and practical transformer, EMF equation, no-load and on-load operation, phasor diagram, equivalent circuit, core and copper losses, Open Circuit (OC) and Short Circuit (SC) tests, voltage regulation, efficiency calculation, Auto-transformer. [6L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "ee-m3-l1",
        lectureNumber: 1,
        title: "EMF Equation & Operation of Single Phase Transformers",
        videoId: "0GHkAVJra-E",
        duration: "7 mins",
        instructor: "Gautam Varde",
        description: "Derivation of E1 = 4.44 * f * N1 * Phi_m, transformation ratio, ideal vs practical transformer losses, and equivalent circuit referred to primary.",
      },
      {
        id: "ee-m3-l2",
        lectureNumber: 2,
        title: "Open Circuit (OC) and Short Circuit (SC) Tests on Transformers",
        videoId: "eSsidG2sk44",
        duration: "31 mins",
        instructor: "Delta Academy (Ranjan Sir)",
        description: "Determining shunt parameters (Rc, Xm) via OC test and series parameters (Req, Xeq) via SC test, voltage regulation, and all-day efficiency.",
      },
    ],
  },
  {
    id: "beee-esee101-mod4",
    moduleNumber: 4,
    moduleLabel: "MODULE 4",
    title: "Electrical Machines: DC Motors & 3-Phase Induction Motors",
    subject: "Basic Electrical and Electronics Engineering (ES-EE101 / ES-EE201)",
    category: "core",
    description: "DC Machine: Construction, working, back EMF, torque-speed characteristics and speed control of separately excited and shunt DC motors. AC Machine: Construction, generation of rotating magnetic fields (RMF) and working of 3-phase induction motor, torque-slip characteristics, 1-phase induction motor, synchronous generator overview. [10L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "ee-m4-l1",
        lectureNumber: 1,
        title: "Electric Machines: DC Motors & AC Induction Machines One-Shot",
        videoId: "Vz1yJaTvb9A",
        duration: "35 mins",
        instructor: "Pradeep Giri Sir",
        description: "DC motor construction, Fleming's left-hand rule, torque equation, armature vs field flux speed control, and induction motor operating principles.",
      },
      {
        id: "ee-m4-l2",
        lectureNumber: 2,
        title: "Production of Rotating Magnetic Field in 3-Phase Induction Motor",
        videoId: "JAPUM3PmvLY",
        duration: "8 mins",
        instructor: "Mind of Engineer",
        description: "Mathematical proof of constant magnitude 1.5 * Phi_m rotating magnetic field at synchronous speed, slip definition, and torque-slip curve.",
      },
    ],
  },
  {
    id: "beee-esee101-mod5",
    moduleNumber: 5,
    moduleLabel: "MODULE 5",
    title: "Bipolar Junction Transistors (BJT) & CE Amplifiers",
    subject: "Basic Electrical and Electronics Engineering (ES-EE101 / ES-EE201)",
    category: "core",
    description: "Transistor Biasing and Bias stability: Stability factor S with variation of Ico. Operating modes: CE, CB, CC and their characteristics. Small signal low frequency operation of transistors, equivalent circuits, h-parameters as two-port network. Transistor as amplifier: Voltage gain, current gain, input/output impedance, frequency response for CE amplifier. [8L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "ee-m5-l1",
        lectureNumber: 1,
        title: "CE, CB, and CC Configurations of Transistors Explained",
        videoId: "x8WxZjKrvTc",
        duration: "16 mins",
        instructor: "Sujal Mane",
        description: "Input and output characteristic curves, alpha, beta, and gamma relationships, and active/saturation/cutoff operating regions.",
      },
      {
        id: "ee-m5-l2",
        lectureNumber: 2,
        title: "Transistor Biasing, Q-Point & Stability Factor",
        videoId: "5T84Jzcgj7M",
        duration: "15 mins",
        instructor: "ALL ABOUT ELECTRONICS",
        description: "DC load line analysis, operating point (Q-point), thermal runaway, fixed bias vs voltage divider self-bias stability comparisons.",
      },
      {
        id: "ee-m5-l3",
        lectureNumber: 3,
        title: "BJT Small Signal Analysis & Common Emitter Amplifier",
        videoId: "wbDUDRlmUuM",
        duration: "19 mins",
        instructor: "ALL ABOUT ELECTRONICS",
        description: "Hybrid-pi and h-parameter models, calculating voltage gain Av, current gain Ai, input impedance Rin, and 180-degree phase reversal in CE amplifiers.",
      },
    ],
  },
  {
    id: "beee-esee101-mod6",
    moduleNumber: 6,
    moduleLabel: "MODULE 6",
    title: "Field Effect Transistors: JFET & MOSFET Characteristics",
    subject: "Basic Electrical and Electronics Engineering (ES-EE101 / ES-EE201)",
    category: "core",
    description: "Construction and characteristics of JFET (N-channel only), Transfer characteristics. Construction and characteristics of MOSFET (N-channel only), depletion and enhancement types; Common Source (CS), Common Gate (CG), Common Drain (CD) configurations. [5L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "ee-m6-l1",
        lectureNumber: 1,
        title: "JFET Construction, Working & Transfer Characteristics",
        videoId: "5mimDymf0g0",
        duration: "18 mins",
        instructor: "Gautam Varde",
        description: "Pinch-off voltage Vp, drain current equation Id = Idss*(1 - Vgs/Vp)^2, drain characteristics, and transconductance gm.",
      },
      {
        id: "ee-m6-l2",
        lectureNumber: 2,
        title: "MOSFET Construction: Enhancement vs Depletion Types",
        videoId: "X4_8dh-J4ik",
        duration: "17 mins",
        instructor: "Gautam Varde",
        description: "Insulated gate structure (SiO2 layer), threshold voltage Vth, inversion layer formation, CS amplifier configuration, and MOSFET switching.",
      },
    ],
  },

  // ==================== NON-CORE SYLLABUS (1ST YEAR B.TECH) ====================
  // 1. Mathematics-I (Paper Code: BS-M101)
  {
    id: "math1-bs101-mod1",
    moduleNumber: 1,
    moduleLabel: "MODULE 1",
    title: "Matrix & Determinant: Rank, Consistency & Eigenvalues",
    subject: "Mathematics-I (BS-M101)",
    category: "non-core",
    description: "Inverse and rank of a matrix; Elementary row and column operations; System of linear equations and consistency; Rank and nullity; Minors and cofactors; Eigenvalues and eigenvectors; Diagonalization of matrices; Cayley-Hamilton theorem; Orthogonal transformation. [8L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "m1-m1-l1",
        lectureNumber: 1,
        title: "Rank of Matrix & Elementary Row/Column Transformations",
        videoId: "ccaHV-ukK2o",
        duration: "38 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Echelon form, row equivalence, finding rank of matrix with short tricks and standard examples.",
      },
      {
        id: "m1-m1-l2",
        lectureNumber: 2,
        title: "Eigenvalues and Eigenvectors: Properties & Characteristic Equations",
        videoId: "1wjXVdwzgX8",
        duration: "24 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Finding eigenvalues, eigenvectors, algebraic/geometric multiplicity, and theorem applications.",
      },
      {
        id: "m1-m1-l3",
        lectureNumber: 3,
        title: "Cayley-Hamilton Theorem & Diagonalization of Matrices",
        videoId: "U8iOTJto8rg",
        duration: "30 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Statement and verification of Cayley-Hamilton theorem, finding matrix inverse and powers, and matrix diagonalization.",
      },
    ],
  },
  {
    id: "math1-bs101-mod2",
    moduleNumber: 2,
    moduleLabel: "MODULE 2",
    title: "Differential Calculus & Sequence and Series",
    subject: "Mathematics-I (BS-M101)",
    category: "non-core",
    description: "Successive derivative, Leibnitz's Theorem; Rolle's Theorem, Mean value theorem, Taylor's and Maclaurin's theorems with remainders; Sequence and Series convergence: Comparison test, Cauchy's Root test, D'Alembert's Ratio test, Raabe's test, Alternating series, Absolute & Conditional convergence. [9L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "m1-m2-l1",
        lectureNumber: 1,
        title: "Successive Differentiation & Leibnitz's Theorem for Nth Derivative",
        videoId: "5etqJRo5pO0",
        duration: "20 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Nth order derivatives of products of functions using Leibnitz's theorem with step-by-step solved engineering problems.",
      },
      {
        id: "m1-m2-l2",
        lectureNumber: 2,
        title: "Rolle's & Mean Value Theorems with Proofs & Solved Problems",
        videoId: "IFtjDDB8fzo",
        duration: "16 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Geometric interpretation and applications of Rolle's theorem, Lagrange's and Cauchy's mean value theorems.",
      },
      {
        id: "m1-m2-l3",
        lectureNumber: 3,
        title: "Convergence of Infinite Series: D'Alembert's Ratio & Cauchy's Root Tests",
        videoId: "inoybBJWsV4",
        duration: "13 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Criteria for convergence of positive term infinite series, ratio test, and root test with typical exam questions.",
      },
    ],
  },
  {
    id: "math1-bs101-mod3",
    moduleNumber: 3,
    moduleLabel: "MODULE 3",
    title: "Integral Calculus: Improper Integrals & Beta-Gamma Functions",
    subject: "Mathematics-I (BS-M101)",
    category: "non-core",
    description: "Improper integrals; Beta and Gamma functions and their properties; Convergence of improper integrals; Applications of definite integrals to evaluate surface areas and volumes of revolutions; Differentiation under integral sign (DUIS / Leibnitz rule). [8L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "m1-m3-l1",
        lectureNumber: 1,
        title: "Beta and Gamma Functions: Definitions, Properties & Formulas",
        videoId: "SduCO-r_TOA",
        duration: "14 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Properties of Gamma and Beta functions, relation between Beta & Gamma, duplication formula, and evaluation shortcuts.",
      },
      {
        id: "m1-m3-l2",
        lectureNumber: 2,
        title: "Improper Integrals: Types, Convergence & Evaluation",
        videoId: "QbrmeGz4hvI",
        duration: "13 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "First kind and second kind improper integrals, test of convergence, and convergence of Beta/Gamma integrals.",
      },
      {
        id: "m1-m3-l3",
        lectureNumber: 3,
        title: "Differentiation Under The Integral Sign (DUIS / Leibnitz Rule)",
        videoId: "6yMaL859Hp8",
        duration: "15 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Leibnitz rule for differentiation under integral sign with variable and constant parameter limits.",
      },
    ],
  },
  {
    id: "math1-bs101-mod4",
    moduleNumber: 4,
    moduleLabel: "MODULE 4",
    title: "Calculus of Function of Several Variables & Multiple Integrals",
    subject: "Mathematics-I (BS-M101)",
    category: "non-core",
    description: "Introduction to functions of several variables; Limit and continuity, Partial derivatives, Homogeneous functions and Euler's theorem, Chain rules, Total differentials, Jacobians, Maxima & minima, Saddle points, Lagrange Multiplier method, Line, Double & Triple integrals. [10L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "m1-m4-l1",
        lectureNumber: 1,
        title: "Partial Differentiation & Euler's Theorem for Homogeneous Functions",
        videoId: "bTs7ncA_AtY",
        duration: "19 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Homogeneous multivariable functions, Euler's theorem proof, and higher-order partial derivative deductions.",
      },
      {
        id: "m1-m4-l2",
        lectureNumber: 2,
        title: "Jacobians: Transformation, Properties & Implicit Functions",
        videoId: "Th_oKIMl94Q",
        duration: "18 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Jacobian matrix determinants, chain rule for Jacobians, and transforming variable coordinates.",
      },
      {
        id: "m1-m4-l3",
        lectureNumber: 3,
        title: "Maxima, Minima & Lagrange's Undetermined Multipliers Method",
        videoId: "FrD7uu6chP0",
        duration: "26 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Necessary and sufficient conditions for extrema of two variables, saddle points, and constrained optimization.",
      },
      {
        id: "m1-m4-l4",
        lectureNumber: 4,
        title: "Double & Triple Integrals: Area and Volume Evaluation",
        videoId: "db7d_a0wiUg",
        duration: "17 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Double integration in Cartesian and polar coordinates, changing order of integration, and triple integral volumes.",
      },
    ],
  },
  {
    id: "math1-bs101-mod5",
    moduleNumber: 5,
    moduleLabel: "MODULE 5",
    title: "Vector Calculus: Point Functions & Integral Theorems",
    subject: "Mathematics-I (BS-M101)",
    category: "non-core",
    description: "Scalar and vector triple products, Straight line, plane and sphere equations. Vector function differentiation, Scalar/vector point functions, Gradient, Divergence and Curl, Directional derivative. Green's theorem, Gauss Divergence Theorem and Stokes' theorem. [10L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "m1-m5-l1",
        lectureNumber: 1,
        title: "Gradient, Divergence and Curl of Vector Point Functions",
        videoId: "csCskd01jwE",
        duration: "11 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Del operator mechanics, solenoidal and irrotational vector fields, physical significance of div and curl.",
      },
      {
        id: "m1-m5-l2",
        lectureNumber: 2,
        title: "Directional Derivative & Unit Normal Vectors to Surfaces",
        videoId: "GrlqXl3xnPk",
        duration: "18 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Rate of change along a vector direction, maximum directional derivative, and tangent plane normals.",
      },
      {
        id: "m1-m5-l3",
        lectureNumber: 3,
        title: "Green's, Gauss Divergence and Stokes' Vector Integration Theorems",
        videoId: "Lpr3u0AZt1U",
        duration: "22 mins",
        instructor: "Dr. Gajendra Purohit",
        description: "Line, surface and volume integral relationships, converting surface to volume integrals, and practical problems.",
      },
    ],
  },

  // 2. Chemistry-I (Paper Code: BS-CH-101 / BS-CH-201)
  {
    id: "chem1-bsch101-mod1",
    moduleNumber: 1,
    moduleLabel: "MODULE 1",
    title: "Thermodynamics, Electrochemistry & Reaction Kinetics",
    subject: "Chemistry-I (BS-CH-101)",
    category: "non-core",
    description: "First & Second Laws, Molar Heat Capacity (Cp vs Cv), Joule-Thomson Coefficient, Carnot Cycle, Entropy, Free Energy, Gibbs-Helmholtz & Maxwell relations. Electrochemistry: Nernst Equation, Cell pH, Batteries, Fuel Cells. Chemical Kinetics: Collision theory, Complex reactions, Michaelis-Menten enzyme catalysis. [11L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "ch-m1-l1",
        lectureNumber: 1,
        title: "First & Second Laws of Thermodynamics and Carnot Cycle",
        videoId: "bN4D8cCibYo",
        duration: "18 mins",
        instructor: "Magnetic Science Institute",
        description: "Carnot engine efficiency, heat capacity relations, Joule-Thomson throttling effect, and entropy change calculations.",
      },
      {
        id: "ch-m1-l2",
        lectureNumber: 2,
        title: "Nernst Equation & Electrochemical Cell Potential",
        videoId: "P-Nu3oNkrpA",
        duration: "24 mins",
        instructor: "Arvind Arora & Adda247",
        description: "Primary/secondary cells, Nernst equation derivation, relation with Delta G, Delta H, Delta S, and cell pH determination.",
      },
      {
        id: "ch-m1-l3",
        lectureNumber: 3,
        title: "Chemical Kinetics & Michaelis-Menten Enzyme Catalysis",
        videoId: "maDAH0ViJj8",
        duration: "29 mins",
        instructor: "All 'Bout Chemistry",
        description: "Rate equations, temperature dependency, Arrhenius activation energy, and enzyme catalysis Michaelis-Menten kinetics.",
      },
    ],
  },
  {
    id: "chem1-bsch101-mod2",
    moduleNumber: 2,
    moduleLabel: "MODULE 2",
    title: "Atomic Structure, Molecular Orbitals & Coordination Chemistry",
    subject: "Chemistry-I (BS-CH-101)",
    category: "non-core",
    description: "Bohr-Sommerfeld model, Quantum numbers, Pauli principle, Hund's rule, Aufbau principle, Hydrogen spectrum, de Broglie hypothesis, Heisenberg uncertainty, Schrodinger equation. VBT, Hybridization, VSEPR, Molecular Orbital Theory (MOT for H2, O2, N2, CO, NO+). Crystal Field Theory (CFT), d-d transitions, Band theory. [8L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "ch-m2-l1",
        lectureNumber: 1,
        title: "Quantum Numbers, Bohr-Sommerfeld Model & Schrodinger Wave Equation",
        videoId: "lcShhzdJHwk",
        duration: "53 mins",
        instructor: "Joydeb Pal / Nimbus Education",
        description: "Shapes of s, p, d, f orbitals, quantum numbers, wave-particle duality, and Schrodinger time-independent equation.",
      },
      {
        id: "ch-m2-l2",
        lectureNumber: 2,
        title: "Molecular Orbital Theory (MOT) & Diatomic Molecule Diagrams",
        videoId: "sAs8ebqUNc8",
        duration: "13 mins",
        instructor: "K2 Chemistry",
        description: "Linear combination of atomic orbitals (LCAO), bonding vs antibonding MOs, bond order, and paramagnetism of O2 and N2.",
      },
      {
        id: "ch-m2-l3",
        lectureNumber: 3,
        title: "Crystal Field Theory (CFT) & Coordination Compounds",
        videoId: "rNQUmESlb_A",
        duration: "16 mins",
        instructor: "Najam Academy",
        description: "Octahedral and tetrahedral crystal field splitting, high spin vs low spin complexes, magnetic properties, and d-d transitions.",
      },
    ],
  },
  {
    id: "chem1-bsch101-mod3",
    moduleNumber: 3,
    moduleLabel: "MODULE 3",
    title: "Organic Spectroscopy: UV-Vis, IR, 1H-NMR & Mass Spectrometry",
    subject: "Chemistry-I (BS-CH-101)",
    category: "non-core",
    description: "UV-Visible: Electronic transitions, chromophores, auxochromes, bathochromic/hypsochromic shifts, Woodward-Fieser rules for conjugated dienes. IR: Modes of molecular vibrations, IR active molecules. 1H-NMR: Chemical shift, shielding/deshielding, equivalent protons. Mass Spectrometry: Ion sources, fragmentation patterns. [7L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "ch-m3-l1",
        lectureNumber: 1,
        title: "UV-Visible Spectroscopy & Woodward-Fieser Rules for Lambda Max",
        videoId: "BZ7_GhnENdY",
        duration: "1 hr 57 mins",
        instructor: "J Chemistry",
        description: "Electronic excitation types, auxochromes, Woodward rules for conjugated dienes and enones, and solvent shift effects.",
      },
      {
        id: "ch-m3-l2",
        lectureNumber: 2,
        title: "IR Spectroscopy: Modes of Molecular Vibrations & Active Molecules",
        videoId: "BU27H9UC3lg",
        duration: "15 mins",
        instructor: "Dr. Anjali Ssaxena",
        description: "Stretching and bending vibrational modes, dipole moment changes, fingerprint region, and functional group identification.",
      },
      {
        id: "ch-m3-l3",
        lectureNumber: 3,
        title: "1H-NMR Spectroscopy: Chemical Shift, Shielding & Deshielding",
        videoId: "qnjW7zJ24Hk",
        duration: "26 mins",
        instructor: "Dr. Anjali Ssaxena",
        description: "Proton resonance principles, TMS standard reference, equivalent vs non-equivalent protons, and peak interpretation.",
      },
    ],
  },
  {
    id: "chem1-bsch101-mod4",
    moduleNumber: 4,
    moduleLabel: "MODULE 4",
    title: "Polymers, Conducting Materials & Corrosion Control",
    subject: "Chemistry-I (BS-CH-101)",
    category: "non-core",
    description: "Molecular weight of polymers (Mn, Mw), addition and condensation polymerization mechanisms, PDI, degree of polymerization, vulcanization, conducting polymers. Corrosion: Dry/wet mechanisms, pitting, crevice, galvanic series. Protection: Sacrificial anode, anodization, passivation, water treatment. [6L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "ch-m4-l1",
        lectureNumber: 1,
        title: "Polymer Chemistry, Polymerization Mechanisms & Conducting Polymers",
        videoId: "HE2zRQVhImw",
        duration: "15 mins",
        instructor: "Engineering Chemistry / TexConnect",
        description: "Addition and condensation polymerization, polydispersity index (PDI), polyacetylene doping, and conducting polymer properties.",
      },
      {
        id: "ch-m4-l2",
        lectureNumber: 2,
        title: "Corrosion Science: Dry/Wet Types & Sacrificial Anode Protection",
        videoId: "FwxP-iC-PFE",
        duration: "25 mins",
        instructor: "Pradeep Giri Sir",
        description: "Electrochemical corrosion mechanism, galvanic corrosion, pitting, stress corrosion cracking, and cathodic protection methods.",
      },
    ],
  },
  {
    id: "chem1-bsch101-mod5",
    moduleNumber: 5,
    moduleLabel: "MODULE 5",
    title: "Stereochemistry & Named Organic Reaction Mechanisms",
    subject: "Chemistry-I (BS-CH-101)",
    category: "non-core",
    description: "Isomerism, Chirality, Optical activity (up to 2 chiral carbons), symmetry elements, Fischer/Newman projections, CIP rules (R/S & E/Z), Ethane and n-butane conformations. Molecular effects: Inductive, resonance, hyperconjugation. Name reactions: Aldol, Cannizzaro, Michael, Claisen-Schmidt, Wittig reactions. [6L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "ch-m5-l1",
        lectureNumber: 1,
        title: "Stereochemistry: Chirality, Fischer/Newman & R/S Nomenclature",
        videoId: "vFkUs_vXxKk",
        duration: "14 mins",
        instructor: "Najam Academy",
        description: "Enantiomers, diastereomers, meso compounds, CIP priority sequence rules for R/S assigning, and staggered/eclipsed conformations.",
      },
      {
        id: "ch-m5-l2",
        lectureNumber: 2,
        title: "Organic Name Reactions: Aldol Condensation & Cannizzaro Mechanisms",
        videoId: "vGSVpd-VP0Y",
        duration: "18 mins",
        instructor: "Najam Academy",
        description: "Carbonyl enolate addition, crossed Aldol condensation, Cannizzaro hydride transfer mechanism, and Michael addition reactions.",
      },
    ],
  },
  {
    id: "chem1-bsch101-mod6",
    moduleNumber: 6,
    moduleLabel: "MODULE 6",
    title: "Chemical Biology, Heavy Metal Toxicity & Drug Synthesis",
    subject: "Chemistry-I (BS-CH-101)",
    category: "non-core",
    description: "Origin of Life, trace and ultratrace elements, role of metal ions in biological systems: Function of Fe (Hemoglobin & Myoglobin) and Cu (Hemocyanin). Heavy metal toxicity (Hg, As, Pb, F, P). Synthesis of commonly used drug molecules: Aspirin, Paracetamol, Salbutamol, Ibuprofen. Synthesis of pesticides: DDT, Lindane, Parathion. [4L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "ch-m6-l1",
        lectureNumber: 1,
        title: "Biomolecules & Metal Ions: Hemoglobin and Myoglobin Biochemistry",
        videoId: "Qv-KExGKAYw",
        duration: "13 mins",
        instructor: "Neural & Knowledge Academy",
        description: "Oxygen transport mechanism of Fe in heme group, cooperative binding, and heavy metal toxicities (mercury, lead, arsenic).",
      },
      {
        id: "ch-m6-l2",
        lectureNumber: 2,
        title: "Synthesis of Important Drug Molecules: Aspirin and Paracetamol",
        videoId: "Yd4Gto1Uzfc",
        duration: "13 mins",
        instructor: "Dr. Vinod Kumari / Er Sahil",
        description: "Acetylation of salicylic acid to synthesize Aspirin, synthesis of Paracetamol from p-aminophenol, and pesticide chemistry (DDT).",
      },
    ],
  },

  // 3. Programming for Problem Solving (Paper Code: ES-CS-101 / ES-CS-201)
  {
    id: "pps-escs101-mod1",
    moduleNumber: 1,
    moduleLabel: "MODULE 1",
    title: "Introduction to Programming, Flowcharts, Expressions & Loops",
    subject: "Programming for Problem Solving (ES-CS-101)",
    category: "non-core",
    description: "Components of a computer system (memory, processor, OS, compilers). Algorithms, flowcharts, pseudocode. Source code, variables, data types, memory layout, syntax and logical errors. Arithmetic expressions & precedence. Conditional branching (if-else, switch) and iteration (for, while, do-while loops). [12L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "pps-m1-l1",
        lectureNumber: 1,
        title: "Computer Architecture & Algorithm Flowcharts with Examples",
        videoId: "QCBV_KrB4wk",
        duration: "23 mins",
        instructor: "Neso Academy & Deck Out",
        description: "Von Neumann architecture, steps to solve logical problems, flowchart standard symbols, and tracing execution paths.",
      },
      {
        id: "pps-m1-l2",
        lectureNumber: 2,
        title: "Operator Precedence, Associativity & Expressions in C",
        videoId: "8H9G621pQq0",
        duration: "17 mins",
        instructor: "Neso Academy",
        description: "Arithmetic, relational, and logical operators, type casting, precedence tables, and evaluating compound C expressions.",
      },
      {
        id: "pps-m1-l3",
        lectureNumber: 3,
        title: "Conditional Branching (If-Else, Switch) & Iterative Loops",
        videoId: "-JMSaLRqsgo",
        duration: "16 mins",
        instructor: "Neso Academy",
        description: "Multiway selection with switch, nested if-else statements, loop control (break, continue), and loop invariant logic.",
      },
    ],
  },
  {
    id: "pps-escs101-mod2",
    moduleNumber: 2,
    moduleLabel: "MODULE 2",
    title: "1D/2D Arrays, Character Strings & Searching/Sorting Algorithms",
    subject: "Programming for Problem Solving (ES-CS-101)",
    category: "non-core",
    description: "1-D and 2-D Arrays, Character arrays, string handling functions. Basic Algorithms: Linear Search, Binary Search. Sorting algorithms: Bubble Sort, Insertion Sort, Selection Sort. Finding roots of equations, notion of order of complexity (Big-O analysis). [12L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "pps-m2-l1",
        lectureNumber: 1,
        title: "1D/2D Arrays & Character Strings in C Programming",
        videoId: "AefKSoNpZtQ",
        duration: "15 mins",
        instructor: "Neso Academy",
        description: "Contiguous memory layout of arrays, row-major order matrix representations, null-terminated strings, and string library functions.",
      },
      {
        id: "pps-m2-l2",
        lectureNumber: 2,
        title: "Searching Algorithms: Linear Search vs Binary Search",
        videoId: "C46QfTjVCNU",
        duration: "24 mins",
        instructor: "Jenny's Lectures CS IT",
        description: "Linear search brute force, binary search divide-and-conquer on sorted arrays, and time complexity comparisons.",
      },
      {
        id: "pps-m2-l3",
        lectureNumber: 3,
        title: "Sorting Algorithms: Bubble Sort, Selection Sort & Insertion Sort",
        videoId: "9oWd4VJOwr0",
        duration: "36 mins",
        instructor: "Jenny's Lectures CS IT",
        description: "Comparative sorting mechanics, element swapping passes, best/average/worst case Big-O analysis and C code implementations.",
      },
    ],
  },
  {
    id: "pps-escs101-mod3",
    moduleNumber: 3,
    moduleLabel: "MODULE 3",
    title: "Modular Functions, Parameter Passing & Recursive Algorithms",
    subject: "Programming for Problem Solving (ES-CS-101)",
    category: "non-core",
    description: "Functions (built-in libraries and user-defined), parameter passing: call by value and call by reference (passing arrays). Recursion as a problem-solving paradigm: Factorial, Fibonacci series, Ackermann function. Divide & conquer sorting: Quick Sort and Merge Sort. [9L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "pps-m3-l1",
        lectureNumber: 1,
        title: "Functions in C: Parameter Passing, Call by Value vs Reference",
        videoId: "HEiPxjVR8CU",
        duration: "19 mins",
        instructor: "Neso Academy",
        description: "Function prototypes, activation stack records, call-by-value immutability, and passing pointers/arrays for simulated call-by-reference.",
      },
      {
        id: "pps-m3-l2",
        lectureNumber: 2,
        title: "Recursion Concepts, Base Conditions & Recursion Trees",
        videoId: "KQZIBckWK-s",
        duration: "19 mins",
        instructor: "Jenny's Lectures CS IT",
        description: "Direct and indirect recursion, stack overflow hazards, and recursive formulations of Factorial, Fibonacci, and Ackermann function.",
      },
      {
        id: "pps-m3-l3",
        lectureNumber: 3,
        title: "Divide & Conquer: Quick Sort and Merge Sort Algorithms",
        videoId: "QN9hnmAgmOc",
        duration: "35 mins",
        instructor: "Jenny's Lectures CS IT",
        description: "Partitioning around pivot in Quick Sort, recursive subarray merging in Merge Sort, and O(n log n) average time complexity.",
      },
    ],
  },
  {
    id: "pps-escs101-mod4",
    moduleNumber: 4,
    moduleLabel: "MODULE 4",
    title: "Structures, Pointers, Dynamic Memory Allocation & File I/O",
    subject: "Programming for Problem Solving (ES-CS-101)",
    category: "non-core",
    description: "Structures, defining structures and arrays of structures, unions. Pointers: Pointer concept, arithmetic, self-referential structures, concept of linked lists. Dynamic memory allocation: malloc, calloc, realloc, free. File handling: File pointers, fopen, fclose, read, write, and append operations. [7L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "pps-m4-l1",
        lectureNumber: 1,
        title: "Structures & Unions in C: Definition, Memory Layout & Padding",
        videoId: "oySsPUDr35U",
        duration: "11 mins",
        instructor: "Neso Academy",
        description: "User-defined composite types, structure member access (dot vs arrow operator), structure arrays, and memory sharing in unions.",
      },
      {
        id: "pps-m4-l2",
        lectureNumber: 2,
        title: "Pointers & Dynamic Memory Allocation (malloc, calloc, free)",
        videoId: "Vch7_YeGKH4",
        duration: "13 mins",
        instructor: "Neso Academy",
        description: "Heap memory allocation, pointer dereferencing, pointer arithmetic, memory leaks, dangling pointers, and self-referential structures.",
      },
      {
        id: "pps-m4-l3",
        lectureNumber: 3,
        title: "File Handling in C: Reading, Writing & Appending Data",
        videoId: "ZIe_j8xAkU4",
        duration: "13 mins",
        instructor: "Jenny's Lectures CS IT",
        description: "Opening file streams with fopen modes (r, w, a), formatted file I/O (fprintf, fscanf), fgetc/fputc, and closing streams with fclose.",
      },
    ],
  },

  // 4. English Language and Technical Communication (Paper Code: HM-HU 101 / HM-HU201)
  {
    id: "eng-hmhu101-mod1",
    moduleNumber: 1,
    moduleLabel: "MODULE 1",
    title: "Theories and Principles of Communication",
    subject: "English Language and Technical Communication (HM-HU101)",
    category: "non-core",
    description: "Theories & Principles of Communication: Definition, Process, Shannon and Weaver's Model of Communication, Verbal and Nonverbal communication, Flows of communication, Barriers to communication. Business communication: Scope of oral communication, self-introduction, introducing others, telephone and video etiquette, paralinguistics. [6L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "eng-m1-l1",
        lectureNumber: 1,
        title: "Shannon-Weaver Model of Communication & Communication Barriers",
        videoId: "j6YIz1QrXtg",
        duration: "12 mins",
        instructor: "Inspire London / Niharika Tiwari",
        description: "Sender, encoder, channel noise, decoder, receiver cycle, psychological/linguistic barriers, and downward/upward organizational flows.",
      },
      {
        id: "eng-m1-l2",
        lectureNumber: 2,
        title: "Oral Business Communication & Professional Presentation Etiquette",
        videoId: "Q074YSGwRTM",
        duration: "12 mins",
        instructor: "WiseUp Communications",
        description: "Body language, tone, pitch, paralinguistic elements, professional introduction protocols, and handling Q&A with brevity.",
      },
    ],
  },
  {
    id: "eng-hmhu101-mod2",
    moduleNumber: 2,
    moduleLabel: "MODULE 2",
    title: "Applied Grammar: Syntax, Transformation & Sentence Synthesis",
    subject: "English Language and Technical Communication (HM-HU101)",
    category: "non-core",
    description: "Common Errors in English: Subject-verb agreement, Tenses, Noun-pronoun agreement, Articles and Prepositions, Misplaced modifiers, Redundancies, Cliches. Sentence transformations: Active and Passive voice, Direct and Indirect speech, Degrees of comparison. Synthesis of sentences: Simple, Complex, and Compound. [9L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "eng-m2-l1",
        lectureNumber: 1,
        title: "Subject-Verb Agreement Rules & Common Error Detection",
        videoId: "zfbUzWqsH74",
        duration: "25 mins",
        instructor: "Dear Sir",
        description: "Golden rules of subject-verb agreement, singular vs plural indefinite pronouns, collective nouns, and common error correction.",
      },
      {
        id: "eng-m2-l2",
        lectureNumber: 2,
        title: "Active & Passive Voice Transformations with Tense Rules",
        videoId: "1rHi6HGYjQc",
        duration: "1 hr 27 mins",
        instructor: "Dear Sir",
        description: "Converting active statements to passive constructions, object pronouns, modal verbs, and using passive voice in technical writing.",
      },
      {
        id: "eng-m2-l3",
        lectureNumber: 3,
        title: "Sentence Synthesis: Simple, Complex & Compound Sentences",
        videoId: "BtT87B3K_9E",
        duration: "28 mins",
        instructor: "Dear Sir",
        description: "Coordinating vs subordinating conjunctions, relative clauses, combining thoughts effectively, and avoiding run-on sentences.",
      },
    ],
  },
  {
    id: "eng-hmhu101-mod3",
    moduleNumber: 3,
    moduleLabel: "MODULE 3",
    title: "Vocabulary Building, Word Formation & Lexical Derivatives",
    subject: "English Language and Technical Communication (HM-HU101)",
    category: "non-core",
    description: "Concept of word formation: Compounding, Backformation, Clipping, and Blending. Root words from foreign languages (Latin, Greek) and their derivatives. Acquaintance with prefixes and suffixes. Synonyms, antonyms, phrasal verbs, one-word substitutions, and standard technical abbreviations. [3L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "eng-m3-l1",
        lectureNumber: 1,
        title: "Word Formation Processes: Compounding, Blending & Affixation",
        videoId: "RmQKoJGMENE",
        duration: "13 mins",
        instructor: "Linguistics Academy",
        description: "How English words are coined: Compounding, portmanteau blending, clipping, backformation, and prefix/suffix morphological additions.",
      },
      {
        id: "eng-m3-l2",
        lectureNumber: 2,
        title: "Vocabulary Mastery: Latin/Greek Roots, Synonyms & Phrasal Verbs",
        videoId: "OLtcFLfYF5o",
        duration: "1 hr 56 mins",
        instructor: "Dear Sir",
        description: "High-frequency root words, prefixes/suffixes, phrasal verbs in professional contexts, and one-word technical substitutions.",
      },
    ],
  },
  {
    id: "eng-hmhu101-mod4",
    moduleNumber: 4,
    moduleLabel: "MODULE 4",
    title: "Basic Writing Skills, Paragraph Cohesion & Technical Documentation",
    subject: "English Language and Technical Communication (HM-HU101)",
    category: "non-core",
    description: "Documenting: Definition, meaning, basic concept in print and online media, types of technical documents. Importance of proper punctuation. Creating coherence: Arranging paragraphs & sentences in logical order. Creating cohesion: Organizing principles of paragraphs in documents. Techniques for writing precisely. [4L]",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    lectures: [
      {
        id: "eng-m4-l1",
        lectureNumber: 1,
        title: "Technical Writing Course: Principles of Engineering Documentation",
        videoId: "vT5pcc30Ffw",
        duration: "1 hr 16 mins",
        instructor: "freeCodeCamp.org",
        description: "Writing documentation for engineering specifications, lab reports, API guides, audience analysis, and clarity over complexity.",
      },
      {
        id: "eng-m4-l2",
        lectureNumber: 2,
        title: "Precis Writing & Creating Coherence and Cohesion in Technical Texts",
        videoId: "sHyWsyoj9kg",
        duration: "14 mins",
        instructor: "Nihir Shah / DWIVEDI Guidance",
        description: "Summarizing technical articles, paragraph structuring, transitional linking devices, punctuation clarity, and conciseness.",
      },
    ],
  },
];

export function getModuleById(id: string): StudyModule | undefined {
  return MODULES_CATALOG.find((m) => m.id === id);
}

export function getSubjectsByCategory(category: "core" | "non-core"): string[] {
  const set = new Set<string>();
  for (const m of MODULES_CATALOG) {
    if (m.category === category) {
      set.add(m.subject);
    }
  }
  return Array.from(set);
}

export function getModulesBySubject(subject: string, category?: "core" | "non-core"): StudyModule[] {
  return MODULES_CATALOG.filter((m) => {
    const matchSubj = m.subject.toLowerCase() === subject.toLowerCase();
    return category ? matchSubj && m.category === category : matchSubj;
  }).sort((a, b) => a.moduleNumber - b.moduleNumber);
}

export function getAllModulesGroupedBySubject() {
  const map: Record<string, StudyModule[]> = {};
  for (const m of MODULES_CATALOG) {
    if (!map[m.subject]) {
      map[m.subject] = [];
    }
    map[m.subject].push(m);
  }
  return map;
}

