-- ============================================================================
-- Supabase Migration: 01_telegram_bot_tickets.sql
-- Description: Sets up bot_tickets table with RLS for Telegram bot interactions
--              and adapts materials table with GIN full-text search index.
-- ============================================================================

-- Ensure required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ----------------------------------------------------------------------------
-- 1. Create the 'bot_tickets' Table
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bot_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  username TEXT,
  type TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  
  -- Constraint: Enforce allowed ticket categories
  CONSTRAINT bot_tickets_type_check 
    CHECK (type IN ('signup_issue', 'material_issue', 'feedback'))
);

-- Performance Indexes for bot_tickets
CREATE INDEX IF NOT EXISTS idx_bot_tickets_user_id 
  ON public.bot_tickets (user_id);

CREATE INDEX IF NOT EXISTS idx_bot_tickets_type 
  ON public.bot_tickets (type);

CREATE INDEX IF NOT EXISTS idx_bot_tickets_created_at 
  ON public.bot_tickets (created_at DESC);

-- ----------------------------------------------------------------------------
-- 2. Configure Row Level Security (RLS) for 'bot_tickets'
-- ----------------------------------------------------------------------------
ALTER TABLE public.bot_tickets ENABLE ROW LEVEL SECURITY;

-- Policy 1: Allow public / anonymous users (e.g., Telegram Bot client using anon key)
--           and authenticated users to INSERT reports/tickets without restrictions.
DROP POLICY IF EXISTS "Allow anon and authenticated insert into bot_tickets" ON public.bot_tickets;
CREATE POLICY "Allow anon and authenticated insert into bot_tickets"
  ON public.bot_tickets
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- Policy 2: Allow administrators to SELECT / review all active tickets
DROP POLICY IF EXISTS "Allow admins to read bot_tickets" ON public.bot_tickets;
CREATE POLICY "Allow admins to read bot_tickets"
  ON public.bot_tickets
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
        AND profiles.role = 'admin'
    )
    OR (select auth.uid()) = '00000000-0000-0000-0000-000000000000'::uuid
  );

-- Policy 3: Allow users or the Telegram bot with anon key to read their own tickets by user_id
DROP POLICY IF EXISTS "Allow users to read own tickets by user_id" ON public.bot_tickets;
CREATE POLICY "Allow users to read own tickets by user_id"
  ON public.bot_tickets
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- ----------------------------------------------------------------------------
-- 3. Verify and Adapt the 'materials' Table
-- ----------------------------------------------------------------------------

-- Ensure materials table exists
CREATE TABLE IF NOT EXISTS public.materials (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  category TEXT,
  file_url TEXT,
  storage_path TEXT,
  video_id TEXT,
  is_temp BOOLEAN NOT NULL DEFAULT false,
  expires_in_seconds INT DEFAULT 3600,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Idempotently add category column if missing
ALTER TABLE public.materials 
  ADD COLUMN IF NOT EXISTS category TEXT;

-- Idempotently add file_url column if missing
ALTER TABLE public.materials 
  ADD COLUMN IF NOT EXISTS file_url TEXT;

-- Update the CHECK constraint to accommodate bot categories ('temp_vault', 'core', 'non_core')
-- while preserving existing portal categories ('non-core', 'temp_pdf', 'lecture')
ALTER TABLE public.materials 
  DROP CONSTRAINT IF EXISTS materials_category_check;

ALTER TABLE public.materials 
  ADD CONSTRAINT materials_category_check
  CHECK (category IN ('core', 'non_core', 'non-core', 'temp_vault', 'temp_pdf', 'lecture'));

-- Add PostgreSQL GIN full-text search index on title for fast keyword retrieval via /search
CREATE INDEX IF NOT EXISTS idx_materials_title_fts 
  ON public.materials 
  USING GIN (to_tsvector('english', title));

-- Ensure RLS is active on materials
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;

-- Ensure public (anon + authenticated) read access policy exists on materials
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'materials' 
      AND policyname = 'Allow public read access to study materials'
  ) THEN
    CREATE POLICY "Allow public read access to study materials"
      ON public.materials
      FOR SELECT
      TO authenticated, anon
      USING (true);
  END IF;
END $$;
